# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' The proposed marginal screening method based on the BKR independence test
#' @name cMBKRall
#' @param Ti is the vector of the ordered censored Time (ascent)
#' @param censor is the censor indicator for the Ti. 1 means no censor and 0 means censoring.
#' @param X is the complete covariates for the samples.
#' @param weight_C the inverse weight in the survival analysis. it is the output of the function KMestimate_CTime.
#' @export
#' @return the cBKRmeasure
NULL

cMBKRall <- function(Ti, censor, X, weight_C) {
    .Call(`_GLASM_cMBKRall`, Ti, censor, X, weight_C)
}

#' calculate the conditional correlation among the X's
#' @param X The data matrix for the X
#' @param betaMat the beta matrix from lasso approach and its variantes. the betaMat can be estimated from the function SPMBgraphsqrtKeh: the sqrt lasso mathod is deployed.
#' @param n the sample nize. 
#' @param d the dimension. 
#' @export
calculate_corrhat <- function(X, betaMat, n, d) {
    .Call(`_GLASM_calculate_corrhat`, X, betaMat, n, d)
}

#' calculate the Test statistics for the independence of X.
#' @param X The data matrix for the X
#' @param betaMat the beta matrix from lasso approach and its variantes. the betaMat can be estimated from the function SPMBgraphsqrtKeh: the sqrt lasso mathod is deployed.
#' @param n the sample nize. dim(X)
#' @param d the dimension. dim(X)
#' @export
calculate_Testhat <- function(X, betaMat, n, d) {
    .Call(`_GLASM_calculate_Testhat`, X, betaMat, n, d)
}

#' sqrt lasso to calculate the betaMat for the X. actually part of the TIGER method
#' @param data The data matrix for the X
#' @param lambda sequence of tuning parameter.
#' @param nlambda the number of lambda sequence.
#' @param d the dimension of X. 
#' @export
SPMBgraphsqrtKeh <- function(data, lambda, nlambda, d) {
    .Call(`_GLASM_SPMBgraphsqrtKeh`, data, lambda, nlambda, d)
}

